[2025-03-08T21:21:26.082+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:26.083+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:26.087+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:26.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:26.097+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:26.094+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 1, in <module>
    from datetime import timedelta, dat
ImportError: cannot import name 'dat' from 'datetime' (/usr/local/lib/python3.12/datetime.py). Did you mean: 'date'?
[2025-03-08T21:21:26.097+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:26.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.045 seconds
[2025-03-08T21:21:28.129+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:28.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:28.133+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:28.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:28.146+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:28.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 7, in <module>
    start_date=datatime, # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:21:28.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:28.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.047 seconds
[2025-03-08T21:21:29.178+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:29.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:29.182+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:29.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:29.189+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:29.186+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 7, in <module>
    start_date=datatime, # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined
[2025-03-08T21:21:29.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:29.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.039 seconds
[2025-03-08T21:21:30.214+0000] {processor.py:186} INFO - Started process (PID=109) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:30.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:30.218+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:30.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:30.238+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:30.235+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 7, in <module>
    start_date=datatime, # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:21:30.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:30.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.065 seconds
[2025-03-08T21:21:31.254+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:31.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:31.257+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:31.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:31.262+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:31.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 7, in <module>
    start_date=datatime, # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:21:31.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:31.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.033 seconds
[2025-03-08T21:21:34.332+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:34.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:34.343+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:34.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:34.350+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:34.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 7, in <module>
    start_date=datatime, # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:21:34.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:34.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.050 seconds
[2025-03-08T21:21:38.365+0000] {processor.py:186} INFO - Started process (PID=118) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:38.366+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:38.368+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:38.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:38.372+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:38.371+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 7, in <module>
    start_date=datatime(2024, ), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:21:38.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:38.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.033 seconds
[2025-03-08T21:21:45.485+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:45.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:45.491+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:45.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:45.497+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:45.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 7, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:21:45.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:45.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.064 seconds
[2025-03-08T21:21:56.641+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:56.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:56.646+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:56.645+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:56.652+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:56.650+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 13, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:21:56.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:56.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.049 seconds
[2025-03-08T21:21:57.739+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:57.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:57.743+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:57.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:57.750+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:57.748+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 15, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:21:57.751+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:57.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.038 seconds
[2025-03-08T21:21:58.750+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:58.751+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:58.754+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:58.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:58.761+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:58.759+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 15, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:21:58.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:58.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.039 seconds
[2025-03-08T21:21:59.822+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:59.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:21:59.825+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:59.825+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:59.832+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:21:59.830+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 15, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:21:59.833+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:21:59.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.034 seconds
[2025-03-08T21:22:01.865+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:01.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:01.871+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:01.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:01.881+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:01.879+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 16, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:22:01.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:01.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.091 seconds
[2025-03-08T21:22:03.939+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:03.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:03.944+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:03.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:03.952+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:03.950+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 17, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:22:03.953+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:03.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.057 seconds
[2025-03-08T21:22:05.002+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:05.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:05.005+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:05.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:05.011+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:05.010+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 17, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:22:05.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:05.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.035 seconds
[2025-03-08T21:22:08.046+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:08.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:08.053+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:08.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:08.065+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:08.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 15, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:22:08.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:08.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.045 seconds
[2025-03-08T21:22:14.177+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:14.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:14.195+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:14.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:14.206+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:14.203+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 14, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:22:14.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:14.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.062 seconds
[2025-03-08T21:22:20.270+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:20.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:20.275+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:20.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:20.285+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:20.281+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 15, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:22:20.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:20.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.043 seconds
[2025-03-08T21:22:22.320+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:22.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:22.329+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:22.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:22.334+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:22.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 15, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:22:22.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:22.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.037 seconds
[2025-03-08T21:22:27.447+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:27.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:27.453+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:27.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:27.464+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:27.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 14, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:22:27.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:27.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.046 seconds
[2025-03-08T21:22:28.488+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:28.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:28.494+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:28.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:28.504+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:28.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mysql_to_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_s3.py", line 14, in <module>
    start_date=datatime(2025, 1, 1), # Start 1 day ago
              ^^^^^^^^
NameError: name 'datatime' is not defined. Did you mean: 'datetime'?
[2025-03-08T21:22:28.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:28.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.049 seconds
[2025-03-08T21:22:29.534+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:29.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:29.539+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:29.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:29.587+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:29.807+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:29.806+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:mysql_to_s3
[2025-03-08T21:22:29.812+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:29.812+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:mysql_to_s3
[2025-03-08T21:22:29.814+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:29.814+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:mysql_to_s3
[2025-03-08T21:22:29.816+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:29.816+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:mysql_to_s3
[2025-03-08T21:22:29.818+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:29.818+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:mysql_to_s3
[2025-03-08T21:22:29.820+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:29.820+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:mysql_to_s3
[2025-03-08T21:22:29.822+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:29.822+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:mysql_to_s3
[2025-03-08T21:22:29.822+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:29.822+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:22:29.834+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:29.833+0000] {dag.py:3262} INFO - Creating ORM DAG for mysql_to_s3
[2025-03-08T21:22:29.841+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:29.841+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:22:29.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.324 seconds
[2025-03-08T21:22:33.970+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:33.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:33.985+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:33.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:34.010+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:34.031+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:34.030+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:22:34.060+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:34.060+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:22:34.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.126 seconds
[2025-03-08T21:22:36.109+0000] {processor.py:186} INFO - Started process (PID=146) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:36.111+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:36.113+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:36.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:36.122+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:36.133+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:36.133+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:22:36.147+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:36.146+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:22:36.157+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.055 seconds
[2025-03-08T21:22:40.186+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:40.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:40.197+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:40.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:40.215+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:40.237+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:40.236+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:22:40.260+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:40.259+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:22:40.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.097 seconds
[2025-03-08T21:22:48.355+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:48.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:48.369+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:48.368+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:48.385+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:48.399+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:48.398+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:22:48.420+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:48.420+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:22:48.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.084 seconds
[2025-03-08T21:22:50.410+0000] {processor.py:186} INFO - Started process (PID=149) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:50.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:50.414+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:50.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:50.427+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:50.443+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:50.442+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:22:50.460+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:50.460+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:22:50.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.068 seconds
[2025-03-08T21:22:52.487+0000] {processor.py:186} INFO - Started process (PID=150) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:52.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:52.489+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:52.489+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:52.498+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:52.510+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:52.510+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:22:52.528+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:52.528+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:22:52.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.061 seconds
[2025-03-08T21:22:53.533+0000] {processor.py:186} INFO - Started process (PID=151) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:53.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:53.543+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:53.543+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:53.563+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:53.578+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:53.578+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:22:53.609+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:53.608+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:22:53.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.105 seconds
[2025-03-08T21:22:55.608+0000] {processor.py:186} INFO - Started process (PID=152) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:55.611+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:22:55.615+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:55.614+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:55.631+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:22:55.651+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:55.651+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:22:55.667+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:22:55.667+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:22:55.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.080 seconds
[2025-03-08T21:23:26.141+0000] {processor.py:186} INFO - Started process (PID=159) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:23:26.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:23:26.146+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:23:26.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:23:26.164+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:23:26.186+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:23:26.186+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:23:26.208+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:23:26.208+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:23:26.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.091 seconds
[2025-03-08T21:23:56.554+0000] {processor.py:186} INFO - Started process (PID=166) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:23:56.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:23:56.559+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:23:56.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:23:56.580+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:23:56.607+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:23:56.607+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:23:56.623+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:23:56.623+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:23:56.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.085 seconds
[2025-03-08T21:24:26.986+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:24:26.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:24:26.994+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:24:26.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:24:27.011+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:24:27.032+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:24:27.032+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:24:27.049+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:24:27.049+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:24:27.058+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.089 seconds
[2025-03-08T21:24:57.418+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:24:57.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:24:57.430+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:24:57.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:24:57.450+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:24:57.470+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:24:57.470+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:24:57.488+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:24:57.488+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:24:57.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.092 seconds
[2025-03-08T21:25:27.773+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:25:27.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:25:27.790+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:25:27.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:25:27.808+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:25:27.832+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:25:27.832+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:25:27.849+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:25:27.849+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:25:27.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.096 seconds
[2025-03-08T21:25:58.113+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:25:58.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:25:58.122+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:25:58.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:25:58.149+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:25:58.172+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:25:58.172+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:25:58.188+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:25:58.188+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:25:58.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.095 seconds
[2025-03-08T21:26:28.505+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:26:28.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:26:28.511+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:26:28.511+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:26:28.540+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:26:28.555+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:26:28.554+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:26:28.573+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:26:28.573+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:26:28.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.089 seconds
[2025-03-08T21:26:58.872+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:26:58.874+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:26:58.878+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:26:58.878+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:26:58.896+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:26:58.914+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:26:58.914+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:26:58.932+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:26:58.932+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:26:58.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.078 seconds
[2025-03-08T21:27:29.223+0000] {processor.py:186} INFO - Started process (PID=215) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:27:29.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:27:29.228+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:27:29.227+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:27:29.244+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:27:29.263+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:27:29.263+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:27:29.284+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:27:29.284+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:27:29.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.080 seconds
[2025-03-08T21:27:59.625+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:27:59.627+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mysql_to_s3.py for tasks to queue
[2025-03-08T21:27:59.632+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:27:59.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:27:59.657+0000] {processor.py:925} INFO - DAG(s) 'mysql_to_s3' retrieved from /opt/airflow/dags/mysql_to_s3.py
[2025-03-08T21:27:59.678+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:27:59.677+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-08T21:27:59.698+0000] {logging_mixin.py:190} INFO - [2025-03-08T21:27:59.698+0000] {dag.py:4180} INFO - Setting next_dagrun for mysql_to_s3 to 2025-03-07 00:00:00+00:00, run_after=2025-03-08 00:00:00+00:00
[2025-03-08T21:27:59.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mysql_to_s3.py took 0.093 seconds
